version: '3.8'

services:
  website:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html
    restart: unless-stopped 
    networks:
      - nginxproxymanager

networks:
  nginxproxymanager:
    external: true 